version: '3'
services:
  node-keystone:
    build:
      context: ./
      dockerfile: node.DOCKERFILE
    ports:
      - "3000:3000"
    environment:
      URLMONGO: 'mongodb://mongo-keystone/textbank'
      MONGOSESSIONURI: 'mongodb://mongo-keystone/textbank-sessions'
      MONGOSESSIONCOLLECTION: 'keystoneSessions'
    env_file:
      - node.env
    volumes:
      - ./:/home/node/app/
  mongo-keystone:
    image: mongo:latest
